version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./master-postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "hataketsu@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgres"